import {ArrowRight} from "lucide-react";import {GlassCard,PageHeader,StatusBadge} from "@/components/shell";
const sections=[
 ["01","What is TxArena?","An autonomous sports market-intelligence arena where deterministic agents analyze the same feed, publish explainable signals, and compete under transparent scoring."],
 ["02","Why TxLINE matters","TxLINE score and odds data is the common source of truth. One normalized feed lets judges compare strategy behavior fairly rather than comparing different inputs."],
 ["03","How data ingestion works","Server-side ingestion obtains match snapshots, converts odds into normalized implied probabilities, stores history in SQLite, and passes typed inputs to every active agent."],
 ["04","Dual-token authentication","Live data requests require both a guest-session JWT and an activated API token. Both credentials remain server-side and neither is exposed to browser code."],
 ["05","Signal scoring","Arena score weights accuracy 35%, confidence calibration 20%, reaction speed 15%, consistency 15%, and volatility awareness 15%. Every dimension is bounded from 0 to 100."],
 ["06","Demo Replay Mode","When live credentials are absent, replay advances all six matches, normalizes new snapshots, executes agents, stores logs, and updates the leaderboard without an external dependency."],
 ["07","Compliance disclaimer","TxArena is an autonomous sports-market intelligence and agent-evaluation tool. It does not execute bets or provide betting advice."]
];
export default function About(){const flow=["TxLINE Feed / Demo Replay","Normalization","Agent Engine","Signal Storage","Scoring Engine","Dashboard / Leaderboard / Logs"];return <div className="mx-auto max-w-[1100px] px-5 py-10"><PageHeader eyebrow="Technical documentation" title="Inside TxArena" subtitle="Architecture, agent logic, scoring, integration boundaries, and responsible product positioning." actions={<StatusBadge tone="purple">Demo Replay Mode</StatusBadge>}/><GlassCard className="mb-5 p-6"><p className="eyebrow">System architecture</p><div className="mt-6 flex flex-wrap items-center gap-3">{flow.map((x,i)=><div key={x} className="contents"><span className="rounded-xl border border-white/10 bg-white/[.03] px-4 py-3 text-xs font-bold">{x}</span>{i<flow.length-1&&<ArrowRight size={15} className="text-lime"/>}</div>)}</div></GlassCard><div className="grid gap-4">{sections.map(s=><GlassCard className="grid gap-5 p-6 md:grid-cols-[70px_220px_1fr]" key={s[0]}><span className="font-mono text-lime">{s[0]}</span><h2 className="font-bold">{s[1]}</h2><p className="text-sm leading-6 text-slate-400">{s[2]}</p></GlassCard>)}</div><GlassCard className="mt-5 p-6"><StatusBadge tone="purple">Server environment</StatusBadge><pre className="mt-5 overflow-x-auto rounded-xl bg-black/30 p-5 font-mono text-xs leading-7 text-cyan">TXLINE_BASE_URL=https://txline.txodds.com{"\n"}TXLINE_GUEST_JWT=server_only_guest_jwt{"\n"}TXLINE_API_TOKEN=server_only_activated_token{"\n"}NEXT_PUBLIC_APP_MODE=demo</pre></GlassCard></div>}
