import {AgentInput,AgentRunner,SignalCandidate} from "@/lib/types";
import {clamp} from "@/lib/probability";
const labels={home:"Home",draw:"Draw",away:"Away"};
const values=(s:AgentInput["latestSnapshot"])=>({home:s.homeProbability,draw:s.drawProbability,away:s.awayProbability});
class Momentum implements AgentRunner{id="agent_momentum";name="Momentum Agent";slug="momentum";strategyType="Trend-following";run(i:AgentInput){if(i.allSnapshots.length<3)return[];const first=values(i.allSnapshots.at(-3)!);const last=values(i.latestSnapshot);const moves=(Object.keys(last) as (keyof typeof last)[]).map(k=>({k,m:last[k]-first[k]})).sort((a,b)=>b.m-a.m);const x=moves[0];return x.m>6?[candidate(this.slug,"MOMENTUM_MOVE",x.k,clamp(58+x.m*2,0,92),x.m,`${labels[x.k]} implied probability increased by ${x.m.toFixed(1)} percentage points across 3 snapshots, exceeding the 6.0 point momentum threshold.`)]:[]}}
class Contrarian implements AgentRunner{id="agent_contrarian";name="Contrarian Agent";slug="contrarian";strategyType="Overreaction detection";run(i:AgentInput){const p=i.previousSnapshots.at(-1);if(!p)return[];const now=values(i.latestSnapshot),old=values(p);const x=(Object.keys(now) as (keyof typeof now)[]).map(k=>({k,m:now[k]-old[k]})).sort((a,b)=>Math.abs(b.m)-Math.abs(a.m))[0];return Math.abs(x.m)>10?[candidate(this.slug,"OVERREACTION_FADE",`fade ${x.k}`,clamp(62+Math.abs(x.m),0,88),Math.abs(x.m),`${labels[x.k]} probability moved sharply by ${Math.abs(x.m).toFixed(1)} percentage points in a short window, triggering the overreaction threshold.`)]:[]}}
class Volatility implements AgentRunner{id="agent_volatility";name="Volatility Agent";slug="volatility";strategyType="Market instability detection";run(i:AgentInput){const p=i.previousSnapshots.at(-1);if(!p)return[];const n=values(i.latestSnapshot),o=values(p);const m=(Object.keys(n) as (keyof typeof n)[]).reduce((s,k)=>s+Math.abs(n[k]-o[k]),0);return m>15?[candidate(this.slug,"HIGH_VOLATILITY","market",clamp(55+m,0,94),m,`Combined probability movement across all outcomes reached ${m.toFixed(1)} percentage points, indicating a high-volatility market window.`)]:[]}}
class Context implements AgentRunner{id="agent_context";name="Context Agent";slug="context";strategyType="Score + time aware";run(i:AgentInput){const p=i.allSnapshots.at(-3);if(!p)return[];const m=i.latestSnapshot.drawProbability-p.drawProbability;const close=Math.abs(i.match.homeScore-i.match.awayScore)<=1;return i.match.minute>70&&close&&m>4?[candidate(this.slug,"LATE_DRAW_PRESSURE","draw",clamp(64+m*2,0,90),m,`After 70 minutes with a close scoreline, draw probability increased by ${m.toFixed(1)} percentage points, triggering late draw pressure.`)]:[]}}
function candidate(agentSlug:string,signalType:string,outcome:string,confidence:number,strength:number,reasoning:string):SignalCandidate{return{agentSlug,signalType,outcome,confidence,strength,reasoning}}
export const agents:AgentRunner[]=[new Momentum(),new Contrarian(),new Volatility(),new Context()];
